### ISSUE TITLE
Move compiled binary files into release

### ISSUE THREAD

**Issue by leofun01** [Wanpaku/Movar#1]
- File [MOVAR-1.0-win64.msi](https://github.com/Wanpaku/Movar/blob/108e8e8caf43767f4748eab8e86bbfa937820cca/Movar%20installer%20Windows%2010/MOVAR-1.0-win64.msi) should be moved from [source](https://github.com/Wanpaku/Movar/tree/108e8e8caf43767f4748eab8e86bbfa937820cca/Movar%20installer%20Windows%2010) to [release](https://github.com/Wanpaku/Movar/releases).
- File [Movar_1.0.tar.gz](https://github.com/Wanpaku/Movar/blob/108e8e8caf43767f4748eab8e86bbfa937820cca/Movar%20launcher%20Manjaro%2023/Movar_1.0.tar.gz) should be moved from [source](https://github.com/Wanpaku/Movar/tree/108e8e8caf43767f4748eab8e86bbfa937820cca/Movar%20launcher%20Manjaro%2023) to [release](https://github.com/Wanpaku/Movar/releases).

**Comment by Wanpaku** [comment]
OK, fixed. Thank you for the comment.
